services:
  prometheus:
    image: prom/prometheus:v2.49.1
    container_name: prometheus
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./infra/prometheus/config.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    ports:
      - "${PROMETHEUS_PORT}:9090"

  node-exporter:
    image: prom/node-exporter:v1.8.1
    container_name: node-exporter
    restart: unless-stopped
    env_file:
      - .env
    # network_mode: host # use if linux, not wsl
    # pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
    ports:
      - "${NODE_EXPORTER_PORT}:9100"

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      prometheus:
        condition: service_started
      loki:
        condition: service_started
    ports:
      - "${GRAFANA_PORT:-3030}:3030"
    env_file:
      - .env
    volumes:
      - grafana-data:/var/lib/grafana
      - ./infra/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    restart: unless-stopped
    ports:
      - "${LOKI_PORT:-3100}:3100"
    volumes:
      - ./infra/loki/loki-config.yml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./infra/promtail/promtail-config.yml:/etc/promtail/config.yml:ro
      - ./logs:/var/log:ro
    command: -config.file=/etc/promtail/config.yml

  log-generator:
    build:
      context: ./log-generator
      dockerfile: Dockerfile
    container_name: log-generator
    restart: "no"
    volumes:
      - ./logs:/var/log
    depends_on:
      - promtail

  shoehub:
    image: aussiearef/shoehub
    container_name: shoehub
    restart: unless-stopped
    ports:
      - "${SHOEHUB_PORT:-8020}:8080"

  mysql:
    image: mysql:8.0.41-debian
    platform: linux/amd64
    container_name: mysql
    environment:
    - MYSQL_DATABASE=${MYSQL_DATABASE:-prometheus}
    - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root}
    ports:
      - "${DOCKER_MYSQL_BIND_PORT:-33077}:3306"
    volumes:
      - mysql-storage:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p${DB_ROOT_PASSWORD:-root} --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    env_file:
      - .env

volumes:
  prometheus-data:
  grafana-data:
  mysql-storage:
  loki-data:
